import type { Metadata } from 'next';
import './globals.css';
import FlyonuiScript from '@/app/components/FlyonuiScript';

export const metadata: Metadata = {
  title: 'Cesta Galega',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" data-theme={'corporate'}>
      <body>{children}</body>
      <FlyonuiScript />
    </html>
  );
}
