import type { Metadata } from 'next';
import './globals.css';
import FlyonuiScript from '@/app/components/FlyonuiScript';
import { AlertProvider } from '@/app/context/AlertContext';
import Alert from '@/app/components/Alert';

export const metadata: Metadata = {
  title: 'Cesta Galega',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" data-theme={'corporate'}>
      <body>
        <div className="mx-auto w-full max-w-[2560px]">
          <AlertProvider>
            <Alert />
            {children}
          </AlertProvider>
        </div>
      </body>
      <FlyonuiScript />
    </html>
  );
}
